version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "=== Environment Information ==="
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -version
      - echo "Environment variables:"
      - printenv | grep -i java || true

  pre_build:
    commands:
      - echo "=== Pre-build phase started on `date` ==="
      - echo "Current directory:"
      - pwd
      - echo "Files in current directory:"
      - ls -la
      - echo "Checking pom.xml:"
      - cat pom.xml | head -20

  build:
    commands:
      - echo "=== Build phase started on `date` ==="
      - echo "Starting Maven build..."
      - mvn clean compile -X -e
      - echo "Maven compile completed, now packaging..."
      - mvn package -DskipTests -X -e
      - echo "=== Build phase completed on `date` ==="

  post_build:
    commands:
      - echo "=== Post-build phase started on `date` ==="
      - echo "Checking target directory:"
      - ls -la target/ || echo "No target directory found"
      - echo "Creating deployment directory..."
      - mkdir -p deployment
      - echo "Copying JAR files:"
      - cp target/*.jar deployment/ || echo "No JAR files found"
      - echo "Copying appspec.yml:"
      - cp appspec.yml deployment/ || echo "appspec.yml not found"
      - echo "Copying scripts directory:"
      - cp -r scripts deployment/ || echo "scripts directory not found"
      - echo "Final deployment directory contents:"
      - ls -la deployment/
      - echo "=== Post-build phase completed on `date` ==="

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-Build-Artifact
