version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Build environment setup..."
      - java -version
      - mvn -version

  pre_build:
    commands:
      - echo "Pre-build phase started on `date`"
      - echo "Nothing to do in pre-build phase"

  build:
    commands:
      - echo "Build phase started on `date`"
      - echo "Compiling the Java application..."
      - mvn clean compile test package -DskipTests
      - echo "Build phase completed on `date`"

  post_build:
    commands:
      - echo "Post-build phase started on `date`"
      - echo "Creating deployment directory..."
      - mkdir -p deployment
      - cp target/*.jar deployment/ || echo "No JAR files found"
      - cp appspec.yml deployment/ || echo "appspec.yml not found"
      - cp -r scripts deployment/ || echo "scripts directory not found"
      - ls -la deployment/
      - echo "Post-build phase completed on `date`"

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-Build-Artifact
