version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
    JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Environment Information"
      - java -version
      - mvn -version
      - echo "MAVEN_OPTS is $MAVEN_OPTS"

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - pwd
      - echo "Listing all files in src directory:"
      - find src -type f -name "*.java" | head -20
      - echo "Checking for main application class:"
      - ls -la src/main/java/com/example/Doc_Ohpp/ || echo "Directory not found"
      - cat src/main/java/com/example/Doc_Ohpp/DocOhppApplication.java || echo "Main class file not found"
      - echo "Resolving Maven dependencies"
      - mvn dependency:resolve -q

  build:
    commands:
      - echo "Build phase started"
      - echo "Maven clean compile with verbose output"
      - mvn clean compile -e -X
      - echo "Checking compiled classes:"
      - find target -name "*.class" | head -10
      - echo "Maven package with verbose output"
      - mvn package -DskipTests -e -X
      - echo "Build completed"
      - ls -la target/

  post_build:
    commands:
      - echo "Post-build phase started"
      - mkdir -p deployment
      - echo "Copying JAR files"
      - cp target/*.jar deployment/
      - echo "Copying appspec.yml"
      - cp appspec.yml deployment/
      - echo "Copying scripts directory if it exists"
      - if [ -d "scripts" ]; then cp -r scripts deployment/; else echo "No scripts directory found, skipping"; fi
      - echo "Deployment directory contents"
      - ls -la deployment/

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-Build-Artifact
