version: 0.2
env:
  variables:
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
    JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m"
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - java -version
      - mvn -version
  pre_build:
    commands:
      - echo "Pre-build phase"
      - mvn dependency:resolve -q
  build:
    commands:
      - echo "Build phase"
      - mvn clean package -DskipTests
  post_build:
    commands:
      - echo "Post-build phase"
      - echo "Listing source scripts directory:"
      - ls -la deployment/scripts/
      - mkdir -p scripts
      - echo "Copying deployment scripts to scripts directory"
      - cp deployment/scripts/*.sh scripts/ || echo "Warning: Script copy failed or no scripts found"
      - echo "Verifying scripts directory contents:"
      - ls -la scripts/
      - echo "Making scripts executable"
      - chmod +x scripts/*.sh || echo "Warning: chmod failed or no scripts found"
      - echo "Creating appspec.yml if not exists at root"
      - test -f appspec.yml || echo "ERROR: appspec.yml not found at project root!"
      - echo "Build complete"
artifacts:
  files:
    - appspec.yml
    - scripts/*.sh
    - scripts/README.md
    - target/*.jar
    - SCRIPTS_PRESENT.txt
  discard-paths: no
