version: 0.2
env:
  variables:
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
    JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m"
phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies"
      - java -version
      - mvn -version
  pre_build:
    commands:
      - echo "Pre-build phase"
      - mvn dependency:resolve -q
  build:
    commands:
      - echo "Build phase"
      - mvn clean package
  post_build:
    commands:
      - echo "Post-build phase"
      - echo "Verifying scripts directory at project root:"
      - ls -la scripts/
      - echo "Making all scripts executable:"
      - chmod +x scripts/*.sh
      - echo "Verifying all required files exist:"
      - test -f appspec.yml && echo "✓ appspec.yml found" || echo "✗ appspec.yml missing"
      - test -f scripts/stop-application.sh && echo "✓ stop-application.sh found" || echo "✗ stop-application.sh missing"
      - test -f scripts/start-application.sh && echo "✓ start-application.sh found" || echo "✗ start-application.sh missing"
      - test -f scripts/install-dependencies.sh && echo "✓ install-dependencies.sh found" || echo "✗ install-dependencies.sh missing"
      - test -f scripts/change-permissions.sh && echo "✓ change-permissions.sh found" || echo "✗ change-permissions.sh missing"
      - test -f scripts/validate-service.sh && echo "✓ validate-service.sh found" || echo "✗ validate-service.sh missing"
      - test -f target/Doc_Ohpp-0.0.1-SNAPSHOT.jar && echo "✓ JAR file found" || echo "✗ JAR file missing"
      - echo "Build artifacts ready for deployment"
artifacts:
  files:
    - appspec.yml
    - scripts/*
    - target/*.jar
  discard-paths: no
