version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
    JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Environment Information"
      - java -version
      - mvn -version
      - echo "MAVEN_OPTS is $MAVEN_OPTS"

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - pwd
      - echo "Checking workspace structure:"
      - ls -la
      - echo "Checking src directory structure:"
      - find src -type f -name "*.java" | head -20 || echo "No Java files found"
      - echo "Verifying main application class:"
      - ls -la src/main/java/com/example/Doc_Ohpp/ || echo "Directory not found"
      - echo "Content check:"
      - find . -name "*.java" -type f | head -10
      - echo "Resolving Maven dependencies"
      - mvn dependency:resolve -q

  build:
    commands:
      - echo "Build phase started"
      - echo "Current directory structure before build:"
      - ls -la
      - echo "Maven clean and compile with detailed output"
      - mvn clean compile -e -X
      - echo "Checking compiled classes after compile:"
      - find target -name "*.class" 2>/dev/null | head -10 || echo "No compiled classes found"
      - echo "Maven package with detailed output"
      - mvn package -DskipTests -e -X
      - echo "Build completed - checking target directory:"
      - ls -la target/ || echo "Target directory not found"

  post_build:
    commands:
      - echo "Post-build phase started"
      - echo "Creating deployment directory"
      - mkdir -p deployment
      - echo "Current directory contents:"
      - ls -la
      - echo "Target directory contents:"
      - ls -la target/ || echo "No target directory"
      - echo "Copying JAR files"
      - find target -name "*.jar" -not -name "*-sources.jar" -not -name "*-javadoc.jar" -exec cp {} deployment/ \; || echo "No JAR files found"
      - echo "Copying appspec.yml"
      - cp appspec.yml deployment/ || echo "appspec.yml not found"
      - echo "Copying scripts directory"
      - if [ -d "scripts" ]; then 
          cp -r scripts deployment/; 
          echo "Scripts copied successfully";
        else 
          echo "Scripts directory not found"; 
        fi
      - echo "Final deployment directory structure:"
      - ls -la deployment/ || echo "Deployment directory not created"
      - if [ -d "deployment/scripts" ]; then
          echo "Scripts in deployment directory:";
          ls -la deployment/scripts/;
        else
          echo "No scripts directory in deployment";
        fi

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-$(date +%Y-%m-%d-%H-%M-%S)
