version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
    JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Environment Information"
      - java -version
      - mvn -version
      - echo "MAVEN_OPTS is $MAVEN_OPTS"

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - pwd
      - ls -la
      - echo "Resolving Maven dependencies"
      - mvn dependency:resolve -q

  build:
    commands:
      - echo "Build phase started"
      - echo "Maven clean compile"
      - mvn clean compile -q
      - echo "Maven package"
      - mvn package -DskipTests -q
      - echo "Build completed"
      - ls -la target/

  post_build:
    commands:
      - echo "Post-build phase started"
      - mkdir -p deployment
      - cp target/*.jar deployment/
      - cp appspec.yml deployment/
      - cp -r scripts deployment/
      - echo "Deployment directory contents"
      - ls -la deployment/

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-Build-Artifact
