version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
    JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "=== Environment Information ==="
      - java -version
      - mvn -version
      - echo "Available memory:"
      - free -h || echo "Memory info not available"
      - echo "MAVEN_OPTS: $MAVEN_OPTS"

  pre_build:
    commands:
      - echo "=== Pre-build phase started ==="
      - pwd
      - ls -la
      - echo "Checking Maven dependencies..."
      - mvn dependency:resolve -q || echo "Dependency resolution failed"

  build:
    commands:
      - echo "=== Build phase started ==="
      - echo "Starting Maven clean compile..."
      - mvn clean compile -q
      - echo "Compile completed successfully"
      - echo "Starting Maven package (skipping tests)..."
      - mvn package -DskipTests -q
      - echo "Package completed successfully"
      - echo "Checking target directory:"
      - ls -la target/

  post_build:
    commands:
      - echo "=== Post-build phase started ==="
      - mkdir -p deployment
      - cp target/*.jar deployment/ 2>/dev/null || echo "No JAR files to copy"
      - cp appspec.yml deployment/ 2>/dev/null || echo "No appspec.yml to copy"
      - cp -r scripts deployment/ 2>/dev/null || echo "No scripts directory to copy"
      - echo "Deployment directory contents:"
      - ls -la deployment/

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-Build-Artifact
