version: 0.2

env:
  variables:
    MAVEN_OPTS: "-Xmx1024m -Xms512m"
    JAVA_TOOL_OPTIONS: "-Xmx1024m -Xms512m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Environment Information"
      - java -version
      - mvn -version
      - echo "MAVEN_OPTS is $MAVEN_OPTS"

  pre_build:
    commands:
      - echo "Pre-build phase started"
      - pwd
      - echo "Checking workspace structure:"
      - ls -la || true
      - echo "Checking src directory structure:"
      - find src -type f -name "*.java" | head -20 || echo "No Java files found"
      - echo "Verifying main application class:"
      - ls -la src/main/java/com/example/Doc_Ohpp/ || echo "Directory not found"
      - echo "Content check (first 10 java files):"
      - find . -name "*.java" -type f | head -10 || true
      - echo "Resolving Maven dependencies"
      - mvn dependency:resolve -q

  build:
    commands:
      - echo "Build phase started"
      - ls -la || true
      - echo "Maven clean compile with detailed output"
      - mvn clean compile -e -X
      - echo "Checking compiled classes after compile:"; find target -name "*.class" 2>/dev/null | head -10 || echo "No compiled classes found"
      - echo "Maven package (skip tests)"; mvn package -DskipTests -e -X
      - echo "Build completed - target directory:"
      - ls -la target/ || echo "Target directory not found"

  post_build:
    commands:
      - echo "Post-build phase started"
      - echo "Normalize line endings (CRLF->LF) & ensure executability for scripts in workspace"
      - if [ -d "scripts" ]; then find scripts -type f -name "*.sh" -exec sed -i 's/\r$//' {} +; chmod +x scripts/*.sh || true; fi
      - echo "Prepare target packaging root"
      - mkdir -p target
      - echo "Copy appspec.yml into target root"
      - cp appspec.yml target/ || echo "appspec.yml missing"
      - echo "Copy full scripts directory into target/scripts"
      - rm -rf target/scripts || true; mkdir -p target/scripts
      - if [ -d scripts ]; then cp -r scripts/* target/scripts/; fi
      - echo "Also copy scripts flat into target root (redundancy)"
      - if [ -d scripts ]; then cp scripts/*.sh target/ 2>/dev/null || true; fi
      - echo "List target root after script copy:"; ls -la target/ || true
      - echo "List target/scripts:"; ls -la target/scripts || true
      - echo "Create diagnostic manifest"
      - (echo "PACKAGED FILES:"; find target -maxdepth 2 -type f -printf '%P\n' 2>/dev/null) > target/SCRIPTS_PRESENT.txt || true
      - cat target/SCRIPTS_PRESENT.txt || true
      - echo "Final target tree (depth 3):"; find target -maxdepth 3 -type f | head -100 || true

artifacts:
  files:
    - '**/*'
  base-directory: target
  name: DocOhpp-artifact-$(date +%Y-%m-%d-%H-%M-%S)
