version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-22-amazon-corretto"
    MAVEN_HOME: "/opt/maven"
    MAVEN_OPTS: "-Xmx1024m"

phases:
  install:
    runtime-versions:
      java: corretto22
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y wget

  pre_build:
    commands:
      - echo "Pre-build phase started on $(date)"
      - echo "Logging in to Amazon ECR (if needed)..."
      - echo "Current directory: $(pwd)"
      - echo "Listing files:"
      - ls -la
      - echo "Java version:"
      - java -version
      - echo "Maven version:"
      - mvn -version
      - echo "AWS CLI version:"
      - aws --version

  build:
    commands:
      - echo "Build phase started on $(date)"
      - echo "Running Maven clean compile..."
      - mvn clean compile -q
      - echo "Running tests..."
      - mvn test
      - echo "Packaging application..."
      - mvn package -DskipTests
      - echo "Build completed on $(date)"
      - echo "Listing target directory:"
      - ls -la target/

  post_build:
    commands:
      - echo "Post-build phase started on $(date)"
      - echo "Build artifacts created:"
      - ls -la target/*.jar
      - echo "Creating deployment directory structure..."
      - mkdir -p deployment
      - cp target/*.jar deployment/
      - cp appspec.yml deployment/ 2>/dev/null || echo "appspec.yml not found, will be created"
      - cp -r scripts deployment/ 2>/dev/null || echo "scripts directory not found, will be created"
      - echo "Deployment directory contents:"
      - ls -la deployment/
      - echo "Post-build phase completed on $(date)"

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-$(date +%Y-%m-%d-%H-%M-%S)

reports:
  junit-reports:
    files:
      - 'target/surefire-reports/*.xml'
    file-format: 'JUNITXML'

cache:
  paths:
    - '/root/.m2/**/*'