version: 0.2

env:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-21-amazon-corretto"
    MAVEN_HOME: "/opt/maven"
    MAVEN_OPTS: "-Xmx1024m"

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y wget

  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - echo "Build started on `date`"
      - echo "Installing dependencies..."
      - yum update -y
      - yum install -y maven

  build:
    commands:
      - echo "Build started on `date`"
      - echo "Compiling the Java application..."
      - mvn clean compile test package
      - echo "Build completed on `date`"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - echo "Creating deployment directory..."
      - mkdir -p deployment
      - cp target/*.jar deployment/
      - cp appspec.yml deployment/
      - cp -r scripts deployment/
      - echo "Deployment package created successfully"

artifacts:
  files:
    - '**/*'
  base-directory: deployment
  name: DocOhpp-$(date +%Y-%m-%d)
